SELECT
P.ANIO+P.SEMESTRE AS semestre_actual,
DAD.CARRERA AS clave_carrera_dgae,
ES.CARRERA AS clave_carrera_facultad,
DAD.PLN_DGAE AS plan_dgae,
ES.PLN AS plan_facultad,
ES.REGISTRO AS semestre_registro,
--MAX(COUNT(BT.SEMESTRE)) AS semestres_baja,
DAD.REGISTRO AS ultimo_semestre,
(CASE ((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) % 10)
WHEN 0 THEN
CASE (2 * ((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) / 10))-1
WHEN -1 THEN 0
ELSE (2 * ((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) / 10))-1 END
ELSE 2 * (((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) / 10) + 1) END) AS semestre_calculo,
ES.PROMEDIO AS promedio,
ES.AVANCE AS avance,
ES.CREDITOS_CUBIERTOS AS creditos_cubiertos,
(CASE
(CASE ((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) % 10)
WHEN 0 THEN (2 * ((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) / 10))-1
ELSE 2 * (((CONVERT(INT,(CASE ES.ULTIMO_CURSADO WHEN '' THEN '{}' ELSE ES.ULTIMO_CURSADO END))-CONVERT(INT,ES.REGISTRO)) / 10) + 1) END)
WHEN -1 THEN 0
WHEN 1 THEN CCP.ASEM01
WHEN 2 THEN CCP.ASEM02
WHEN 3 THEN CCP.ASEM03
WHEN 4 THEN CCP.ASEM04
WHEN 5 THEN CCP.ASEM05
WHEN 6 THEN CCP.ASEM06
WHEN 7 THEN CCP.ASEM07
WHEN 8 THEN CCP.ASEM08
WHEN 9 THEN CCP.ASEM09
ELSE CCP.ASEM10 END) AS creditos_esperados,
(SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO) AS alumnos_generacion,
(SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CARRERA=ES.CARRERA) AS alumnos_generacion_carrera,
(CASE (SELECT 100 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND ES2.AVANCE>=100)
WHEN 100 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CARRERA=ES.CARRERA AND ES2.AVANCE>=100)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CARRERA=ES.CARRERA AND ES2.AVANCE>=ES.AVANCE) END) AS lugar_generacion,
(CASE
(CASE ((CONVERT(INT,DAD.REGISTRO)-CONVERT(INT,ES.REGISTRO)) % 10)
WHEN 0 THEN (2 * ((CONVERT(INT,DAD.REGISTRO)-CONVERT(INT,ES.REGISTRO)) / 10))-1
ELSE 2 * (((CONVERT(INT,DAD.REGISTRO)-CONVERT(INT,ES.REGISTRO)) / 10) + 1) END)
WHEN 1 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM01>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM01 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 2 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM02>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM02 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 3 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM03>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM03 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 4 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM04>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM04 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 5 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM05>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM05 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 6 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM06>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM06 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 7 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM07>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM07 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 8 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM08>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM08 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
WHEN 9 THEN (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM09>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM09 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
ELSE (CASE (SELECT 1 FROM ESTUDIA_SERIACION ES2 WHERE ES2.CUENTA=ES.CUENTA AND ES2.PLN=ES.PLN AND ES2.CARRERA=ES.CARRERA AND CCP.ASEM10>ES2.AVANCE)
WHEN 1 THEN (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=ES.CREDITOS_CUBIERTOS AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA)
ELSE (SELECT COUNT(*) FROM ESTUDIA_SERIACION ES2 WHERE ES2.REGISTRO=ES.REGISTRO AND ES2.CREDITOS_CUBIERTOS>=CCP.ASEM10 AND ES2.PROMEDIO>ES.PROMEDIO AND ES2.CARRERA=ES.CARRERA) END)
END) AS lugar_carrera
FROM  PERIODO P, DIR_ALUMNOS_DGAE DAD
LEFT JOIN ESTUDIA_SERIACION ES
ON DAD.CUENTA=RIGHT('000000000'+ES.CUENTA,9)
LEFT JOIN BAJAS_TEMPORALES BT
ON DAD.CUENTA=RIGHT('000000000'+BT.CUENTA,9)
LEFT JOIN CRED_SEM_CARR_PLN CCP
ON ES.PLN=CCP.PLN
WHERE DAD.CUENTA=?
AND DAD.PLN_DGAE=ES.PLN_DGAE
AND ES.CARRERA=CCP.CARRERA